### ISSUE TITLE
[Set] 프로젝트 초기 설정

### ISSUE THREAD

**Issue by meltsplit** [TeamZOOC/ZOOC-iOS#1]
## 🛠 Issue
- 프로젝트 초기 설정

## 📋 To-do
- [x] Issue, Pull Request 템플릿 생성
- [x] gitignore 파일 생성
- [x] Xcode 프로젝트 생성 및 폴더링
- [x] Storyboard 파일 삭제
- [x] SPM 추가
- [x] 네트워킹 http 차단 풀기
- [x] Extension 파일 추가
- [x] 폰트 추가
- [x] 색상 추가
