### ISSUE TITLE
[Feat] 온보딩 플로우 정리

### ISSUE THREAD

**Issue by meltsplit** [TeamZOOC/ZOOC-iOS#105]
## 🛠 Issue
- 온보딩 플로우 정리

## 📋 To-do
- [x] 가족 생성 잘 되는지
- [x] 펫 데이터 서버로 넘어가는지
- [ ] 펫 등록하기뷰 오류 없는지
- [x] 펫 등록하기 사진 변경 
- [x] 가족생성코드 정확한 코드 오는지
