### ISSUE TITLE
[Feat] 자동로그인 구현

### ISSUE THREAD

**Issue by meltsplit** [TeamZOOC/ZOOC-iOS#107]
## 🛠 Issue
- 자동 로그인 구현

## 📋 To-do
- [x] 자동로그인 구현
- [x] UserDefaultWrapper 객체 생성
- [x] 로그인 플로우 정립
- [ ] 푸시알람으로 앱 들어왔을 때 정상적으로 로그인 되는 지 확인
- [x] UserModel 싱글톤 모델 유저정보 다루는게 맞을까?
