### ISSUE TITLE
[Refactor] 전체 QA 후 변경사항 적용 

### ISSUE THREAD

**Issue by HELLOHIDI** [TeamZOOC/ZOOC-iOS#116]
## 🛠 Issue
- 전체 QA 후 변경사항 적용 

## 📋 To-do
- [x] 마이페이지 초대하기 기능 구현
- [x] 반려동물 기본 이미지 카메라 변경
- [x] 프로필 수정 첫 진입시 “/10” 으로 나오는 부분 수정
- [x] 반려동물 등록 뷰 셀 크기 수정
- [x] 반려동물 사진 변경 수정
- [x] 반려동물 API 송출 버튼 눌렀을 때 버튼 diable 처리
