### ISSUE TITLE
[Feat] 홈뷰 UI 구현하기

### ISSUE THREAD

**Issue by meltsplit** [TeamZOOC/ZOOC-iOS#12]
## 🛠 Issue
- 홈뷰 UI 구현하기

## 📋 To-do
- [ ] 컬렉션뷰 Diffable Data Source
- [ ] 컬렉션뷰 Compositional Layout
- [ ] 선택시 펼쳐지는 UI
