### ISSUE TITLE
[Feat] 상세보기 UI 변경 및 스와이프 기능 구현

### ISSUE THREAD

**Issue by meltsplit** [TeamZOOC/ZOOC-iOS#124]
## 🛠 Issue
- 상세보기 UI 변경

## 📋 To-do
- [ ] 댓글 trailing 수정
- [ ] 좌우 스와이프시 페이지 이동 구현
- [ ] 내친김에 BaseVC에 좌->우 스와이프시 pop기능 구현할까봐~
