### ISSUE TITLE
[Refactor] 마이페이지, 홈 뷰 리펙토링

### ISSUE THREAD

**Issue by HELLOHIDI** [TeamZOOC/ZOOC-iOS#129]
## 🛠 Issue
- 마이페이지, 홈 뷰 리펙토링

## 📋 To-do
- [x]  프로필편집에서 페이지 나가시겠어요 버튼 활성화
- [ ]  탈퇴하기 버튼 눌러도 화면 안바뀜 이슈
- [ ]  앱 정보 부분 Leading값 맞춰야할듯
- [x]  펫 기본 이미지 설정 할 수 있도록 변경
- [ ]  가족 컬렉션뷰 이름도 잘리네. 이거 디자인 선생님과 얘기해야할듯.
- [ ]  펫 이미지 등록할 때 처음 들어가면 버튼 두번 눌러야 갤러리 나오는 이슈 해결
- [ ]  프로필 편집뷰에서 프로필사진 우측하단에 카메라버튼 동그라미로 만들기
- [ ] 홈 화면 기록하기에서 전체보기 누르면 이미지 indexing이 가운데가 비어있음 해결해야됨 ⇒ 기기대응 문제일 가능성이 있다
- [ ] 홈 화면에서 기록이 없는 펫을 누르면 다른 펫 정보로 넘어갈 수 없음
