### ISSUE TITLE
[Feat] 기록하기 뷰 UI 구현

### ISSUE THREAD

**Issue by yunsun99** [TeamZOOC/ZOOC-iOS#13]
## 🛠 Issue
- 기록하기 뷰 UI 구현

## 📋 To-do
- [ ] 기록하기 뷰 UI 구현
- [ ] 키보드 처리
- [ ] textField에 글 유무에 따라 버튼 활성화/비활성화
- [ ] 뒤로가기 버튼 클릭 시 alert 창 띄우기
