### ISSUE TITLE
[Feat] 사진 전체화면 및 다운로드 기능 구현

### ISSUE THREAD

**Issue by meltsplit** [TeamZOOC/ZOOC-iOS#152]
## 🛠 Issue
- 사진 전체화면 및 다운로드 기능 구현

## 📋 To-do
- [ ] 사진 선택시 전체화면 띄우기
- [ ] 사진 다운로드 기능 구현하기
- [ ] 아카이빙뷰 비율 개선
