### ISSUE TITLE
[Refactor] 코드 리팩토링 

### ISSUE THREAD

**Issue by meltsplit** [TeamZOOC/ZOOC-iOS#16]
## 🛠 Issue
- 코드 리팩토링 

## 📋 To-do
- [x] 폰트 추가
- [x] 색상 추가
- [x] Lottie SPM 추가
- [x] Firebase - Messaging SPM 추가
- [ ] 네이밍 리팩토링
- [ ] 코드 컨벤션 수정
