### ISSUE TITLE
[Fix] 기획 QA - 기록하기 미션하기 관련 이슈 해결

### ISSUE THREAD

**Issue by HELLOHIDI** [TeamZOOC/ZOOC-iOS#160]
## 🛠 Issue
- 기획 QA - 기록하기 미션하기 관련 이슈 해결

## 📋 To-do
- [x] 미션하기 사진 선택시 갤러리창 dismiss 처리
- [x] 반려동물 추가 버튼 클릭시 button 비활성화 처리
- [x] 반려동물 사진 선택시 갤러리창 dismiss 처리
- [x] 알림설정 스크롤 관련 문제 해결
- [x] 미션하기 index 오류 해결하기
- [ ] 미션하기에 등록한 게시물 안나오는 이슈 해결
- [x] 미션하기 기록하기 기기대응
