### ISSUE TITLE
[Fix] 마이페이지 UI 수정

### ISSUE THREAD

**Issue by HELLOHIDI** [TeamZOOC/ZOOC-iOS#18]
## 🛠 Issue
- 마이페이지 UI 수정
## 📋 To-do
- [x] 마이페이지 UI 변경
- [x] 알림설정 UI 변경
- [x] 마이페이지 회원탈퇴 UI 구성
