### ISSUE TITLE
[Feat] 등록 플로우 UI 구현

### ISSUE THREAD

**Issue by yunsun99** [TeamZOOC/ZOOC-iOS#21]
## 🛠 Issue
- 등록 플로우 뷰 UI 구현
- 등록 완료 뷰 구현

## 📋 To-do
- [ ] 등록 플로우 뷰 UI 구현
- [ ] 반려동물 수에 따른 분기 처리
- [ ] 반려동물 선택 시 backgroundColor, border, fontcolor 변경 (중복 가능)
- [ ] 등록 완료 뷰 구현
- [ ] 화면 전환 구현
