### ISSUE TITLE
[Refactor] 마이페이지 뷰, 온보딩 뷰 수정

### ISSUE THREAD

**Issue by HELLOHIDI** [TeamZOOC/ZOOC-iOS#25]
## 🛠 Issue
-  마이페이지 뷰, 온보딩 뷰 수정
## 📋 To-do
- [x] 온보딩 after delay 뷰 수정 
- [x] 온보딩 프로그레스 바 구현
- [ ] 온보딩 코드복사에서 코드 복사하기
- [ ] 온보딩 코드 길이에 따른 버튼 활성화 분기처리 하기
- [ ] 온보딩  반려동물 등록하기 버튼 활성화 분기처리 하기
- [ ] 온보딩 시작화면 로티 적용하기
- [x] 마이페이지 뷰 반려동물 초대 UI 구현
- [x] 마이페이지 가족 뷰에서 가장 앞에 자신이 제일 앞에 오도록
- [x] 파일 리네이밍
