### ISSUE TITLE
[Feat] AutoLayout 깨지는 현상 수정

### ISSUE THREAD

**Issue by yunsun99** [TeamZOOC/ZOOC-iOS#45]
## 🛠 Issue
- AutoLayout 깨지는 현상 수정

## 📋 To-do
- [ ] iPhone SE 2 에서 확인
- [ ] iPhone 13 mini 에서 확인
- [ ] iPhone 13 Pro 에서 확인
