### ISSUE TITLE
[Feat] 온보딩 AutoLayout 깨지는 현상 수정(후반부)

### ISSUE THREAD

**Issue by yunsun99** [TeamZOOC/ZOOC-iOS#52]
## 🛠 Issue
- 온보딩 후반부의 AutoLayout 깨지는 현상 수정

## 📋 To-do
- [ ] iPhone SE2 테스트
- [ ] iPhone 13 Pro 테스트
- [ ] iPhone 13 mini 테스트
