### ISSUE TITLE
[Fix] QA 반영하기

### ISSUE THREAD

**Issue by yunsun99** [TeamZOOC/ZOOC-iOS#56]
## 🛠 Issue
- QA 반영하기

## 📋 To-do
- [ ] 여러 alert 뷰에서 label의 background color 확인
- [ ] 마이페이지 컬렉션 뷰 뒤쪽 inset이 좀 더 필요해 보임
- [ ] 키보드 내려가는 것도 구현해야 함
