### ISSUE TITLE
[Fix] UI관련 QA 반영하기 

### ISSUE THREAD

**Issue by HELLOHIDI** [TeamZOOC/ZOOC-iOS#57]
## 🛠 Issue
-  UI관련 QA 반영하기 

## 📋 To-do
- [ ] 알람창 tableviewcell 선택 시 selectionStyle 변경
- [ ] 마이페이지 가족, 반려동물 CollectionView inset 추가
- [ ] 마이페지이 가족, 반려동물 구성원 수 라벨 AutoLayout 수정
