### ISSUE TITLE
[Refactor] 홈뷰 코드 리팩토링

### ISSUE THREAD

**Issue by meltsplit** [TeamZOOC/ZOOC-iOS#64]
## 🛠 Issue
- 홈뷰 코드를 수정해봅시다

## 📋 To-do
- [x] IndicatorView 잘 안되는 오류 해결하기
- [x] 코드 컨벤션 지키기
- [x] API 함수 호출부 깔끔하게 하기
- [x] MVC 패턴 로드뷰로 할까?
- [x] Then 라이브러리 do 함수 사용
