### ISSUE TITLE
[Refactor] 상세보기뷰 리팩토링

### ISSUE THREAD

**Issue by meltsplit** [TeamZOOC/ZOOC-iOS#68]
## 🛠 Issue
- 상세보기뷰 코드를 수정해봅시다

## 📋 To-do
- [x] Then 라이브러리 do 함수 사용
- [x] 코드 컨벤션 지키기
- [x] commentCollectionView Layout 오류 해결하기
- [x] API 함수 호출부 깔끔하게 하기
