### ISSUE TITLE
[Fix] 상세보기뷰 키보드 높이에 따라 뷰 올라가지 않는 오류

### ISSUE THREAD

**Issue by meltsplit** [TeamZOOC/ZOOC-iOS#71]
## 🛠 Issue
- 상세보기 뷰에서 댓글 작성시 키보드 올라올때 뷰가 올라가지 않는 오류가 발생함

## 📋 To-do
- [ ] 스크롤뷰 오토레이아웃 잘 확인하기
- [ ] 스크롤뷰와 contentView의 연관관계 확인해보기
- [ ] LayoutGuide, frameGuide 알아보기
- [ ] textField의 내부 프로퍼티 더 알아보기
