### ISSUE TITLE
[Feat] 프로필 수정, 앱 정보 이용약관 UI 구성

### ISSUE THREAD

**Issue by HELLOHIDI** [TeamZOOC/ZOOC-iOS#9]
## 🛠 Issue
- 프로필 수정, 앱 정보 이용약관 UI 구성

## 📋 To-do
- [x] 프로필 수정 UI 구성
- [x] 앱 정보 이용약관 UI 구성
- [x] 마이페이지에서 프로필 수정 페이지로 화면 이동
- [x] 마이페이지에서 앱 정보 이용약관 페이지로 화면 이동
